#!/bin/sh

set -a  # mark all variables below as exported (environment) variables

# Indentify this script as source of job configuration
K8S_CONFIG_SOURCE=${BASH_SOURCE[0]}

K8S_NUM_GPU=0  # max of 2 (contact ETS to raise limit)
K8S_NUM_CPU=1  # max of 8 ("")
K8S_GB_MEM=2  # max of 64 ("")

# Controls whether an interactive Bash shell is started
SPAWN_INTERACTIVE_SHELL=YES

# Do not disable Jupyter proxy - see ticket CS0493759 (https://support.ucsd.edu/nav_to.do?uri=sn_customerservice_case.do?sys_id=cbfb91fc1befe010df40ed7dee4bcb4e%26sysparm_view=case)
PROXY_ENABLED=YES

K8S_DOCKER_IMAGE="stevenjswanson/cse142l-runner:v26"

K8S_ENTRYPOINT="/opt/conda/bin/jupyter-notebook"

exec /software/common64/dsmlp/bin/launch.sh "$@"
